### ISSUE TITLE
Add version key to manifest

### ISSUE THREAD

**Issue by edmundask** [kairoaraujo/kodak-smart-home#2]
Recently I've tried adding this integration via HACS, but was shown a warning in the logs that the integration does not have a `version` key in the manifest file. The [official docs](https://developers.home-assistant.io/docs/creating_integration_manifest#version) state that the version key is required for custom integrations:

> For core integrations, this should be omitted.
>
> The version of the integration is required for custom integrations. The version needs to be a valid version recognized by AwesomeVersion like CalVer or SemVer.

Related PRs:
* https://github.com/home-assistant/core/pull/45523
* https://github.com/home-assistant/developers.home-assistant/pull/780

**Comment by edmundask** [comment]
The referenced commit does not seem to address the issue, as I'm still getting the warning in the logs:

> [homeassistant.loader] No 'version' key in the manifest file for custom integration 'kodak_smart_home'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'kodak_smart_home'

So the manifest should include the `version` key:

```json
{
  "domain": "kodak_smart_home",
  "name": "Kodak Smart Home",
  "documentation": "https://www.home-assistant.io/integrations/kodak_smart_home",
  "requirements": ["python-kodaksmarthome==0.1.3b1"],
  "dependencies": ["ffmpeg"],
  "codeowners": ["@kairoaraujo"],
  "version": "<VERSION.NUMBER.HERE>",
}
```

**Comment by kairoaraujo** [comment]
My bad, I did a mistake.

**Comment by kairoaraujo** [comment]
Release https://github.com/kairoaraujo/kodak-smart-home/releases/tag/1.0.2
