### ISSUE TITLE
Add support for Australia

### ISSUE THREAD

**Issue by mfav01** [kairoaraujo/kodak-smart-home#4]
I was wondering if it would be possible to please add support for Australia? 

I am really hoping to get this to work as it would be a great integration. 

Thanks, Mark

**Comment by kairoaraujo** [comment]
Hi @mfav01 Mark,

Are you familiar with Python code? Maybe you could create a Pull Request after testing by yourself.
I would be happy to receive this Pull Request.

It needs to be done here: https://github.com/kairoaraujo/python-kodaksmarthome/blob/master/kodaksmarthome/constants.py 

See a similar PR (https://github.com/kairoaraujo/python-kodaksmarthome/pull/20)

**Comment by mfav01** [comment]
Thanks @kairoaraujo.  
I have attempted to edit the code, I am just working out how to run the tests. I have not used GitHub or tested code in HA before. I will submit the pull request once tested. 
[](https://github.com/mfav01/python-kodaksmarthome/blob/au-support_a01/kodaksmarthome/constants.py)

**Comment by xlr82xs** [comment]
Australia uses the same configuration as IN currently.

**Comment by mfav01** [comment]
Hi all, thank you for your help. I can confirm Australia is working using the IN configuration. @kairoaraujo appreciate your work on this component. 

Hopefully live streaming will also be possible soon.
