### ISSUE TITLE
Too many clicking on EU server

### ISSUE THREAD

**Issue by cociweb** [kairoaraujo/kodak-smart-home#9]
Hello,

I'm tryng to configure the integration It's not an easy run, with the outdated pip-ed version (0.1.1) on docker versions. :)
Anyway, I've pimped it without pip: successfully from source to 0.1.3b3, but...

I've tried to set up, and unfortunatelly, I get this on EU server and after it an 'invalid config' notification:

```
Logger: custom_components.kodak_smart_home
Source: custom_components/kodak_smart_home/__init__.py:68
Integration: kodak_smart_home
First occurred: 1:06:18 (1 occurrences)
Last logged: 1:06:18

Unable to fetch camera from Kodak Smart Home Portal: Unexpected HTTP CODE error <!DOCTYPE html>

<html lang="en"> <head> <meta charset="utf-8"> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>503 HTML Template by Ebuynow</title>

    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css?family=Cabin:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:900" rel="stylesheet">

    <!-- Custom stlylesheet -->
    <link type="text/css" rel="stylesheet" href="css/style.css" />

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
              <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
              <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
            <![endif]-->
</head> <body>
    <div id="notfound">
            <div class="notfound">
                    <div class="Warning-404">
                            <h3>Oops! Too many time click to page</h3>
                    </div>
                    <h2>we are sorry, but you must wait several seconds to access again!</h2>
            </div>
    </div>
</body> </html>
```
```
Logger: homeassistant.setup
Source: setup.py:173
First occurred: 1:06:20 (1 occurrences)
Last logged: 1:06:20

Setup failed for kodak_smart_home: Integration failed to initialize.
```
```
Logger: homeassistant.setup
Source: setup.py:311
First occurred: 1:06:20 (1 occurrences)
Last logged: 1:06:20

Unable to prepare setup for platform kodak_smart_home.camera: Unable to set up component.
```

I've also tried the US server, but there is no this kind of error. (it's only unable to initializate the module due 'invalid config', but it's could be reasonable since my device is on the eu server). Only:

> ```
> Logger: homeassistant.setup
> Source: custom_components/kodak_smart_home/__init__.py:61
> Integration: kodak_smart_home
> First occurred: 1:00:16 (1 occurrences)
> Last logged: 1:00:16
> 
> Error during setup of component kodak_smart_home
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/setup.py", line 249, in _async_setup_component
>     result = await task
>   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/kodak_smart_home/__init__.py", line 61, in setup
>     hass_kodak.connect()
>   File "/usr/local/lib/python3.9/site-packages/kodaksmarthome/api.py", line 320, in connect
>     self._authentication()
>   File "/usr/local/lib/python3.9/site-packages/kodaksmarthome/api.py", line 231, in _authentication
>     self.cookie = self.http_session.cookies["JSESSIONID"]
>   File "/usr/local/lib/python3.9/site-packages/requests/cookies.py", line 328, in __getitem__
>     return self._find_no_duplicates(name)
>   File "/usr/local/lib/python3.9/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
>     raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
> KeyError: "name='JSESSIONID', domain=None, path=None"
> ```

Unfortunatelly, there is no further clue, what is going on (are we before or after the authentication....). Nothing is parsed,
Please note there was a very similar issue [here](https://github.com/kairoaraujo/python-kodaksmarthome/issues/3) by You. Also Let me add that it was never worked for me with previous versions as well.

Do you have any hints what is going on?
Latest hassio, HACS, HA, device firmware, python 3.9.

**Comment by kairoaraujo** [comment]
Hi @cociweb, 
Thank you for your issue. 
Yes, I notice the same, and I will need to fix it, reducing call numbers to the API. 
It is a work in progress

**Comment by cociweb** [comment]
Great, Thanks!
In the meantime let me close this issue to avoid the duplication.
